### ISSUE TITLE
Changing the list

### ISSUE THREAD

**Issue by shanedrgn** [alcat2008/react-drag-list#2]
Changing the source list (adding/removing) messes up the display of the list.

**Comment by anuragCES** [comment]
@alcat2008 

Any update on this issue?

**Comment by clarabatt** [comment]
same problem

**Comment by anuragCES** [comment]
@clarabatt 

I went ahead and create my own wrapper of the sortablejs to fix this.

I might be able to get a PR out to fix the issue here too. But I recommend you to try your own wrapper.

**Comment by clarabatt** [comment]
@anuragCES are you could shared you code with me? Is in any repo on your github?

**Comment by anuragCES** [comment]
@clarabatt 

I'm sorry, I haven't pushed it for open source yet. Hmm..let me see if I can provide you a gist for it.

Is it alright for you if I get back to you tomorrow?

**Comment by clarabatt** [comment]
@anuragCES 
Ok, tomorrow it's look like for me.
When you push can mark me or send me a email (clarabattesini@gmail.com)?

Thank you!

**Comment by anuragCES** [comment]
Will do 👍

**Comment by Shaharsha** [comment]
Hi!
I'm issuing the same problem, can you share your code that resolves the problem please?

**Comment by anuragCES** [comment]
@Shaharsha

Here's a gist I created for this issue -

https://gist.github.com/anuragCES/625d3753990b9aa7725754ce074f2b8c

Let me know if it works out for you.

Thanks.

**Comment by ComputerCarl** [comment]
After spending several hours trying to figure out how to use the oldIndex and newIndex to manipulate the state and handle items being dynamically added and removed, I had an idea to do it another way.
Since the drag list always in the order I wanted the items, I instead read the DOM;

In the list component, I set a data attribute;
````js
<div style={styles.row} data-shortcode={card.shortCode}>{card.title}</div>
````
..and then select it (and eventually save it)
````js
    componentDidUpdate(prevProps, prevState) {
        if (prevProps.type !== 'current') return;
        let els = document.querySelectorAll('[data-shortcode')
        let domList = [...els].map(el => el.dataset.shortcode)
        console.log({ domList });
    }
````

**Comment by alcat2008** [comment]
[feat: return updated dataSource after drag end, add rowKey for render](https://github.com/alcat2008/react-drag-list/commit/dabfd6fe647edf7b70ad7d34420668117778aabc) , please refer to this
