### ISSUE TITLE
How disable draggend ?

### ISSUE THREAD

**Issue by GuillermoParedes** [alcat2008/react-drag-list#5]
How disable draggend ?

**Comment by ComputerCarl** [comment]
I am using conditional rendering of the `ReactDragList` component and a standard `arr.map()`, but a disable prop would be a nice addition to a great component!

**Comment by alcat2008** [comment]
thanks for your ideas, it's support now, please refer to
https://github.com/alcat2008/react-drag-list/commit/deead988fd4cf54284d3c62ae328a8da1b98aaa4
